version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
  client0:
    build:
      context: ./
      dockerfile: Dockerfile.client
    environment:
      - CID=0
  client1:
    build:
      context: ./
      dockerfile: Dockerfile.client
    environment:
      - CID=1
