"""Generate docs/inversion/ — the manifest and, until the real figures land,
visibly-placeholder panels.

The gradient-inversion reconstructions are produced on feat/secagg-live and do
not exist here yet. Rather than block the explainer on them, the explainer is
built against the manifest as a declared contract: it reads
docs/inversion/manifest.json, picks the undefended attack by
`noise_multiplier == 0` and the defended one by `noise_multiplier > 0`, and
renders whatever PNGs the manifest names.

Swapping the real images in is therefore a file copy plus a manifest edit:
drop the PNGs into docs/inversion/, point the manifest at them, set
`placeholder` false, and adjust `caption` to the condition actually run. No
code changes, in the dashboard or here. `tests/test_explainer_assets.py`
enforces the schema and that every referenced file exists.

Run:  python scripts/build_inversion_placeholders.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _flatpanel import GROUND_RAISED, INK, RULE, Canvas  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "inversion"

PANEL = 320

# The defended arm's condition is the one the run actually used, read from the
# committed phase-B record rather than retyped here.
BATCH_B = json.loads((ROOT / "docs" / "_final_batch_b.json").read_text(encoding="utf-8"))
CALIBRATED_Z: float = BATCH_B["calibrated_z"]
ACHIEVED_EPSILON: float = BATCH_B["achieved_epsilon"]


def placeholder_panel(role: str, condition: str) -> bytes:
    """A flat panel that reads as a placeholder from across the room.

    Deliberately not an image: no texture, no grey noise, nothing that could be
    screenshotted and mistaken for a reconstruction.
    """
    canvas = Canvas(PANEL, PANEL, GROUND_RAISED)
    canvas.frame(inset=0, thickness=1, colour=RULE)
    canvas.text_centred(96, role, 3, INK)
    canvas.text_centred(126, "PENDING", 3, INK)
    canvas.rect(56, 166, PANEL - 112, 1, RULE)
    canvas.text_centred(190, condition, 2, INK)
    canvas.text_centred(244, "PLACEHOLDER - NOT A RESULT", 2, INK)
    return canvas.to_png()


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    arms = [
        {
            "id": "undefended",
            "batch_size": 1,
            "noise_multiplier": 0.0,
            "epsilon": None,
            "original_png": "original_b1_z0.png",
            "reconstruction_png": "reconstruction_b1_z0.png",
            "caption": (
                "One client, one example in the batch, one local step, no defence. "
                "Reconstructed from the submitted update alone — the raw data never "
                "left the client, and it did not have to."
            ),
            "placeholder": True,
            "_panel_condition": "B=1 Z=0.00 NO DEFENCE",
        },
        {
            "id": "defended",
            "batch_size": 1,
            "noise_multiplier": CALIBRATED_Z,
            "epsilon": ACHIEVED_EPSILON,
            "original_png": f"original_b1_z{CALIBRATED_Z:.3f}.png",
            "reconstruction_png": f"reconstruction_b1_z{CALIBRATED_Z:.3f}.png",
            "caption": (
                "The same attack, the same client, the same batch — run against the "
                "clipped and noised update instead. Same optimiser, same number of "
                "steps."
            ),
            "placeholder": True,
            "_panel_condition": f"B=1 Z={CALIBRATED_Z:.3f} CLIPPED",
        },
    ]

    entries = []
    for arm in arms:
        condition = str(arm.pop("_panel_condition"))
        (OUT / str(arm["original_png"])).write_bytes(placeholder_panel("ORIGINAL", condition))
        (OUT / str(arm["reconstruction_png"])).write_bytes(
            placeholder_panel("RECONSTRUCTION", condition)
        )
        entries.append(arm)

    manifest = {
        "schema_version": 1,
        "note": (
            "Gradient-inversion figures for the explainer. Paths are relative to "
            "this file. The explainer selects the undefended arm by "
            "noise_multiplier == 0 and the defended arm by noise_multiplier > 0, so "
            "replacing the images is a file copy plus an edit here — no code change. "
            "While `placeholder` is true the panels are generated by "
            "scripts/build_inversion_placeholders.py and are not results."
        ),
        "entries": entries,
    }
    (OUT / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"wrote {OUT / 'manifest.json'} and {2 * len(entries)} panels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
